version: '3.7'

services:
  app:
    container_name: sw-app
    build: 
      context: .
      target: dev
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
      